#define 				COLOR_YELLOW 							0xFFFF00AA
#define 				COLOR_RED 								0xE60000FF
#define 				COLOR_WHITE 							0xFFFFFFAA
#define 				COLOR_LIGHT								0xAFD9FAFF
#define 				COLOR_GREY 								0xCECECEFF
#define 				COLOR_PURPLE 							0xC2A2DAAA
#define                 COLOR_LIGHTRED                          0xFF8080FF
#define 				COLOR_NICESKY 							0x00C2ECFF
#define 				COLOR_GREEN 							0x00FF00AA
#define                 COLOR_TEAL                              0x67AAB1FF
#define 				COLOR_DCHAT		 						0xFFD7004A
#define                 COLOR_CHATBUBBLE						0xFFFFFFCC
#define                 COLOR_NEWBIE							0xBED9EFFF
#define                 COLOR_RADIOCHAT                         0x8D8DFFFF
#define                 COLOR_GENANNOUNCE                   	0xA9C4E4FF
#define					COLOR_COOLBLUE							0x0064FFAA
#define 				COLOR_HOTORANGE 						0xF97804FF
#define					COLOR_SMS								0xD5EAFFFF
#define                 EMBED_GREY                          	"{CECECE}"
#define                 EMBED_LIGHTRED                          "{FF8080}"
#define                 EMBED_OOC                               "{AFD9FA}"
#define                 EMBED_WHITE                             "{FFFFFF}"